'use client';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import './page.scss';
import Layout from '../components/Layout/Layout';
import { ThemeProvider } from 'next-themes';
import { Provider } from 'react-redux';
import { store } from '../store';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/146e2842-fd5a-4cd2-92f3-338f3c7f3aeb.png"
        />
      </head>
      <body className={`antialiased app h-screen`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <Provider store={store}>
            <Layout children={children} />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
